name: Compatibility with pyiron_atomistics Notebooks

on:
  push:
env:
  PYIRON_BASE_BRANCH: ${{ vars.PYIRON_BASE_BRANCH }}
  PYIRON_ATOMISTICS_BRANCH: ${{ vars.PYIRON_ATOMISTICS_BRANCH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Merge environment
      run: |
        git clone https://github.com/pyiron/pyiron_base
        cd pyiron_base
        git checkout ${PYIRON_BASE_BRANCH} 
        cd ..
        git clone https://github.com/pyiron/pyiron_atomistics
        cd pyiron_atomistics
        git checkout ${PYIRON_ATOMISTICS_BRANCH}
        cd ..
        cp pyiron_atomistics/.ci_support/environment.yml environment.yml
        tail --lines=+4 pyiron_atomistics/.ci_support/environment-notebooks.yml >> environment.yml
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        environment-file: environment.yml
        use-mamba: true
    - name: Tests
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        pip install versioneer[toml]==0.29
        cd pyiron_atomistics
        pip install . --no-deps --no-build-isolation
        cd ../pyiron_base
        pip install . --no-deps --no-build-isolation
        cd ../pyiron_atomistics
        ./.ci_support/build_notebooks.sh
